server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/blog?serverTimezone=Asia/Seoul
    username: cos
    password: spring
    
  jpa:
    open-in-view: true 
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #SpringPysicalNamingStrategy 전략을 쓰면 필드가 만약 myEmail이라 정리하면 테이블에 my_email로 들어간다.
      use-new-id-generator-mappings: false # false를 사용하면 jpa가 사용하는 기본 넘버링 전략을 따라가지 않는다
    show-sql: false
    properties:
      hibernate.format_sql: true # 정렬된 상태의 sql문을 볼 수 있다.

  jackson:
    serialization:
      fail-on-empty-beans: false